#!/usr/bin/env bash

# Author: w0rp <devw0rp@gmail.com>, hauleth <lukasz@niemier.pl>
# Description: This script wraps DMD so we can get something which is capable of reading
#   D code from stdin.

set -eu

traverse() {
  path=$(pwd)
  while [ "$path" != "/" ] \
    && ! [[ -e "$path/dub.json" || -e "$path/dub.sdl" || -e "$path/package.json" ]]
  do
    path=$(dirname "$path")
  done

  echo "$path"
}

import_line_options() {
  root="$(traverse)"

  if [[ -e "$root/dub.json" || -e "$root/dub.sdl" || -e "$root/package.json" ]]
  then
    dub describe --root="$root" --import-paths | awk '{ print "-I" $0 }'
  else
    echo -n
  fi
}

temp_dir=$(mktemp -d 2>/dev/null || mktemp -d -t 'ale_linters')
temp_file="$temp_dir/file.d"
trap 'rm -r "$temp_dir"' EXIT

cp /dev/stdin "$temp_file"

dmd $(import_line_options) "$@" "$temp_file"
