#!/usr/bin/env bash

# Author: w0rp <devw0rp@gmail.com>
# Description: This script wraps DMD so we can get something which is capable of reading
#   D code from stdin.

set -eu

traverse() {
  path=$(pwd)
  while [ "$path" != "/" ] \
    && ! [[ -e "$path/dub.json" || -e "$path/dub.sdl" || -e "$path/package.json" ]]
  do
    path=$(dirname "$path")
  done

  echo "$path"
}

temp_dir=$(mktemp -d 2>/dev/null || mktemp -d -t 'ale_linters')
temp_file="$temp_dir/file.d"
trap 'rm -r "$temp_dir"' EXIT

cp /dev/stdin "$temp_file"

# Read imports from DUB.
dub_root=$(traverse)
import_line_options=$(dub describe --root="$dub_root" --import-paths | awk '{ print "-I" $0 }' || echo -n)

dmd $import_line_options "$@" "$temp_file"
