#!/usr/bin/env bash

file_path="$1"

temp_dir=$(mktemp -d 2>/dev/null || mktemp -d -t 'ale_linter')
temp_file="$temp_dir/$(basename "$file_path")"
trap 'rm -r "$temp_dir"' EXIT

cat > "$temp_file"

package=$(grep '^package ' "$temp_file")

for filename in $(dirname "$file_path")/*.go; do
    if [ $(basename "$filename") != $(basename "$file_path") ]; then
        if [ "$package" == "$(grep '^package ' "$filename")" ]; then
            cp $filename $temp_dir
        fi
    fi
done

(go build -o /dev/null "$temp_dir"/*.go 3>&1 1>&2 2>&3 | grep "$temp_file") 3>&1 1>&2 2>&3
