#!/usr/bin/env bash

# Author: w0rp <devw0rp@gmail.com>
# Description: This script implements a wrapper for any program which does not accept
#   stdin input on most Unix machines. The input to the script is read to a
#   temporary file, and the first argument sets a particular file extension
#   for the temporary file.

set -e

# All of the following arguments are read as command to run.
file_extension="$1"
shift

temp_file=$(mktemp "ale-XXXXXXXXX$file_extension")
trap 'rm $temp_file' EXIT

cat > "$temp_file"

"$@" "$temp_file"
